swagger: "2.0"
definitions:
  instanceTemplateNetworkInterfaceSpec:
    x-jdcloud-module: vm
    required:
      - subnetId
    properties:
      subnetId:
        type: string
        description: Subnet ID
      securityGroups:
        type: array
        items:
          type: string
        description: List of ID Security Group
      sanityCheck:
        type: integer
        description: PortSecurity, the value is 0 or 1, 1 by default