swagger: "2.0"
definitions:
  image:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: Image ID
      name:
        type: string
        description: Image name
      platform:
        type: string
        description: OS Release version. Ubuntu, CentOS, Windows Server
      osVersion:
        type: string
        description: OS version.
      architecture:
        type: string
        description: Image architecture. i386, x86_64
      systemDiskSizeGB:
        type: integer
        description: Image system disk size
      imageSource:
        type: string
        description: "image source,  jcloud: public image,  marketplace: image marketplace,  image self: user's own image share: image shared by other users"
      osType:
        type: string
        description: OS type. Value: [windows, linux]
      status:
        type: string
        description: <a href="https://www.jdcloud.com/help/detail/3871/isCatalog/1">参考镜像状态</a>
      createTime:
        type: string
        format: date-time
        description: Creation time
      sizeMB:
        type: integer
        description: Image document size
      desc:
        type: string
        description: Image description
      systemDisk:
        $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: System disk configuration
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: Package image data disk mapping information
      snapshotId:
        type: string
        description: The snapshot ID of the cloud disk for creating the system disk of the cloud disk, when the system disk type is image of the local disk, this parameter is blank.
      rootDeviceType:
        type: string
        Description: "The system disk type supported by the image. localDisk: Support system disk for this site.cloudDisk: Support cloud disk system disk"
      progress:
        type: string
        description: "progress in image replication,  in percentage,  for example: 80"
